### PR TITLE
Update readme

### LINKED ISSUE #2: [DOCS] Format README a little better.
README.md looks great, but can be improved, by adding some badges, etc. I can work on this.

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Description

Add badges, fix spelling and grammer issues

Fixes #2 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Adarsh-jaiss — APPROVED** [review]
-- looks awesome

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss you want the size badge?

**Comment by Adarsh-jaiss** [comment]
It's upon you 😄, add what suits according to the project 😄

**Comment by KendallDoesCoding** [comment]
> It's upon you 😄, add what suits according to the project 😄

I think size is on the brim, but let it be for now!

**Pull request merged**
